### DISCUSSION TITLE
Custom Resource with Coder

### DISCUSSION THREAD

**Discussion by framctr** [coder/coder#13884] [General] [answered]
I'm trying to create a Custom Resource when launching a Workspace and I tried to use the [`kubernetes_manifest`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) resource, but I get the following error:
```
The plugin returned an unexpected error from plugin.(*GRPCProvider).PlanResourceChange: rpc error: code = Unknown desc = failed to determine resource type ID: failed to look up GVK [ray.io/v1, Kind=RayCluster] among available CRDs: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:coder:coder" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

I set the following custom values in the Coder helm chart, but it does not change anything:
```yaml
   coder:
      serviceAccount:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["ray.io/v1"]
            resources: ["*"]
            verbs: ["*"]
```

Am I missing something?

**Comment by kylecarbs** [comment]
Are you certain the provisioned workspace is using this service account?

**Comment by framctr** [comment]
Yes. I'm not sure, but could it be related to the fact coder has a Role instead of ClusterRole? CRDs could require ClusterRole

**Comment by ericpaulsen** [comment]
@framctr can you confirm the permissions are properly being passed to the coder role?

```
kubectl get role coder-workspace-perms -n <namespace> -o yaml
```

**Reply by framctr** [reply]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  labels:
    app.kubernetes.io/managed-by: Helm
  name: coder-workspace-perms
  namespace: coder
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ray.io/v1
  resources:
  - '*'
  verbs:
  - '*'

**Reply by ericpaulsen** [reply]
@framctr looks good. its possible the ClusterRole is needed to access/provision your CRDs, as you mention above.

**Reply by framctr** [reply, marked as answer]
Ok thank you @ericpaulsen . I figured out how to solve.

To list CRDs I need a `ClusterRole` as we said and I added the role to the `ServiceAccount` used by Coder. Here the code:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coder-workspace-crds
rules:
  - apiGroups: ["apiextensions.k8s.io"] # list CRDs
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-workspace-crds
subjects:
  - kind: ServiceAccount
    name: coder
    namespace: coder
    apiGroup: "" # default for service accounts
roleRef:
  kind: ClusterRole
  name: coder-workspace-crds
  apiGroup: rbac.authorization.k8s.io
```

I also needed to specify a rule to create the Ray clusters and I decided to do that in the Coder helm chart values, but it is possible to do that also in the ClusterRole if it is needed in some use cases:
```yaml
coder:
      serviceAccount:
        extraRules:
          - apiGroups: ["ray.io"] # required for Terraform `kubernetes_manifest` resources
            resources: ["*"]
            verbs: ["*"]
```

Thank you all
