### DISCUSSION TITLE
Workspace build failed terraform apply: exit status 1

### DISCUSSION THREAD

**Discussion by KD-MM2** [coder/coder#14993] [General] [answered]
```
Starting workspace
0 seconds
Terraform 1.9.2
docker_image.main: Plan to create
docker_container.workspace[0]: Plan to create
docker_image.main: Creating...
docker_image.main: Creation errored after 0s
Error: failed to read downloaded context: failed to load cache key: invalid response status 403

on main.tf line 167, in resource "docker_image" "main":
  167: resource "docker_image" "main" {
Cleaning Up
```

my compose file:
```
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    ports:
      - "3016:7080"
    env_file: .env
    restart: unless-stopped
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:16"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - /mnt/OTHER_DATAS/coder_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
```
![image](https://github.com/user-attachments/assets/3025ff87-d8ef-49da-9a3e-3d7a8915bca9)

**Comment by matifali** [comment]
Hi @KD-MM2 could you share your Dockerfile? Is it a multistage build?
This usually happens when an instruction is trying to COPY a file from outside if build context. 
See https://forums.docker.com/t/dockerfile-getting-failed-to-compute-cache-key-in-the-build/125911/6 for more context.

**Reply by KD-MM2** [reply, marked as answer]
@matifali 

SOLVED!

Sorry my bad, I was use the example Docker containers template.
and it was related to DNS problem. Checked the DNS configs, then I was able to get Coder working.

My working compose file:
```
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    ports:
      - "0.0.0.0:3016:80"
    networks:
      - coder_net
    env_file: .env
    restart: unless-stopped
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      CODER_WILDCARD_ACCESS_URL: "${CODER_WILDCARD_ACCESS_URL}"
      CODER_HTTP_ADDRESS: "${CODER_HTTP_ADDRESS}"
      CODER_TLS_ENABLE: "${CODER_TLS_ENABLE}"
      CODER_TLS_ADDRESS: "${CODER_TLS_ADDRESS}"
      CODER_REDIRECT_TO_ACCESS_URL: "${CODER_REDIRECT_TO_ACCESS_URL}"
      CODER_DOCS_URL: "${CODER_DOCS_URL}"
      CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS: "${CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS}"
      CODER_OAUTH2_GITHUB_ALLOW_EVERYONE: "${CODER_OAUTH2_GITHUB_ALLOW_EVERYONE}"
      CODER_OAUTH2_GITHUB_CLIENT_ID: "${CODER_OAUTH2_GITHUB_CLIENT_ID}"
      CODER_OAUTH2_GITHUB_CLIENT_SECRET: "${CODER_OAUTH2_GITHUB_CLIENT_SECRET}"
      CODER_TELEMETRY: "${CODER_TELEMETRY}"
    user: root
    privileged: true
    group_add:
      - "999" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:16"
    restart: unless-stopped
    networks:
      - coder_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - /mnt/OTHER_DATAS/coder_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  coder_net:
    external: false
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
``` 

/etc/resolv.conf:
```
nameserver 127.0.0.53
options edns0 trust-ad
search .
```

my router doesn't support nat loopback so I added this to /etc/hosts :
```
192.168.0.2 coder.example.com  <--- hostname
```

coder container's /etc/resolv.conf:
```
nameserver 127.0.0.11
search .
options edns0 trust-ad ndots:0
```

ping from container:
```
ping coder.example.com
PING coder.example.com (192.168.0.2): 56 data bytes
64 bytes from 192.168.0.2: seq=0 ttl=64 time=0.064 ms
64 bytes from 192.168.0.2: seq=1 ttl=64 time=0.084 ms
```
