### DISCUSSION TITLE
Access kubernetes service from Coder

### DISCUSSION THREAD

**Discussion by framctr** [coder/coder#15027] [General]
I'm using coder on Kubernetes to deploy both a workspace and another deployment. The last one exposes a dashboard through a `Service` resource.

Is it possible to make the dashboard accessible through Coder, for example using the `coderd.coder_app` Terraform resource? I would like to give to the user a button on the dashboard to access this dashboard.

**Comment by kylecarbs** [comment]
Is the service network accessible? If so, you can provide that URL as a Coder app in the dashboard.

**Reply by framctr** [reply]
Yes, I was trying to do that. I added the `services` to the Coder workspaces' `ServiceAccount` and I'm giving the URL of the service to access as a Coder app. The service is in the same namespace as the Coder installation and workspace and I tested the connection with `curl` from a pod launched in the same namespace, and it works.
I don't know if I'm doing something wrong with Coder. My configuration is:
```hcl
resource "coder_app" "dashboard" {
  agent_id     = coder_agent.main.id
  display_name = "Dashboard"
  icon         = "/icon/desktop.svg"
  url       = "http://dashboard-<username>-<user_workspace_name>-head-svc.coder.svc.cluster.local:8265"
  slug      = "dashboard"
  subdomain = false
  share     = "owner"
}
```

As I said, I can curl `http://dashboard-<username>-<user_workspace_name>-head-svc.coder.svc.cluster.local:8265` from the workspace.

Error:
```
502 - Bad Gateway
Failed to proxy request to application: dial context: connect tcp [fd7b:115c:b1e1:450d:cc48:e7e:36be:7c78]:8265: connection was refused
```

**Reply by matifali** [reply]
This is interesting. I guess this could be related to how Coder reverse proxies the URL. @Emyrk, do you have any suggestions on what might be happening here?

**Reply by Emyrk** [reply]
I am guessing this error occurs on the UI.
This could be a red herring, but could this be an ipv6 issue? I see the error includes an ipv6 address. I have never tested an ipv6 address myself.

**Reply by framctr** [reply]
Yes I noticed this IPv6 address too and it is quite strange to me because I'm using only IPv4 in my cluster..

Some additional info on this lab setup:
- Versions: kubernetes v1.28.10 +rke2r1, Coder v2.16.0
- The lab is in VPN
- The cluster is using Calico with `bgp: Disabled`
- both cluster and service CIDRs are IPv4 only
- OpenStack Load Balancer associated to the NGINX ingress controller with PROXY protocol
- NGINX ingress controller with the following configs and annotations:
    - `controller.dnsPolicy: ClusterFirstWithHostNet`
    - `controller.hostNetwork: false`
    - `controller.hostPort: false`
    - `service.externalTrafficPolicy: "Local"` 
    - `config.use-proxy-protocol: true`
    - `extraArgs.enable-ssl-passthrough: true`
    - `annotations.loadbalancer.openstack.org/proxy-protocol: "true"`

In the Coder helm values I added:
```yaml
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          value: postgres://redacted
        - name: CODER_ACCESS_URL
          value: "http://redacted.sslip.io"
      ingress:
        enable: true
        className: nginx
        host: redacted.sslip.io
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
      service:
        type: ClusterIP
      serviceAccount:
        extraRules:
          - apiGroups: ["networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["*"]
          - apiGroups: [""]
            resources: ["services"]
            verbs: ["*"]
```
