### DISCUSSION TITLE
Permission denied when running as a docker container

### DISCUSSION THREAD

**Discussion by nguyenthanhtien** [coder/coder#15960] [General] [answered]
I cloned and run docker-compose, but i dont know how Coder can connect to Docker. While i Create Template from Docker, it's show:

> Warning: Argument is deprecated
> on main.tf line 28, in resource "coder_agent" "main":
>   28:   startup_script_timeout = 180
> This feature is deprecated and has no effect. This attribute will be removed in a future version of the provider.
> Error: Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
> on main.tf line 19, in provider "docker":
>   19: provider "docker" {
> Warning: Argument is deprecated
> on main.tf line 28, in resource "coder_agent" "main":
>   28:   startup_script_timeout = 180
> This feature is deprecated and has no effect. This attribute will be removed in a future version of the provider.
> 

docker-compose.yaml
> 
> version: "3.9"
> services:
>   coder:
>     # This MUST be stable for our documentation and
>     # other automations.
>     image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
>     ports:
>       - "7080:7080"
>     environment:
>       CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
>       CODER_HTTP_ADDRESS: "0.0.0.0:7080"
>       # You'll need to set CODER_ACCESS_URL to an IP or domain
>       # that workspaces can reach. This cannot be localhost
>       # or 127.0.0.1 for non-Docker templates!
>       CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
>     # If the coder user does not have write permissions on
>     # the docker socket, you can uncomment the following
>     # lines and set the group ID to one that has write
>     # permissions on the docker socket.
>     group_add:
>      - "998" # docker group on host
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     depends_on:
>       database:
>         condition: service_healthy
>   database:
>     image: "postgres:14.2"
>     ports:
>       - "5432:5432"
>     environment:
>       POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
>       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
>       POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
>     volumes:
>       - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
>     healthcheck:
>       test:
>         [
>           "CMD-SHELL",
>           "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
>         ]
>       interval: 5s
>       timeout: 5s
>       retries: 5
> volumes:
>   coder_data:
> 
> 

.env
> 
> # Coder must be reachable from an external URL for users and workspaces to connect.
> # e.g. https://coder.example.com
> CODER_ACCESS_URL=http://localhost:7080/
> 
> CODER_HTTP_ADDRESS=http://localhost:7080/
> CODER_PG_CONNECTION_URL=
> CODER_TLS_CERT_FILE=
> CODER_TLS_ENABLE=
> CODER_TLS_KEY_FILE=
> 
> # Run "coder server --help" for flag information.
>

**Comment by matifali** [comment]
For docker you can use `--group_add` to add the container user to the docker group.

**Comment by matifali** [comment]
We should add an FAQ or a troubleshooting section to Docker installation docs, as this is a common issue.
cc: @stirby

**Comment by thejezzi** [comment]
I have the same problem. I added my docker group id in the docker compose file under `group_add` but it still shows the same error while creating a workspace with the provided docker template: `Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied`

**Comment by is-jonreeves** [comment]
If you are running "Docker on Windows" this worked for me (Windows 10):
```yaml
...
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    user: ${PUID}:${PGID} # <--- NEEDED
    environment:
      ...
      PUID: ${PUID} # <--- NEEDED
      PGID: ${PGID} # <--- NEEDED
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
...
```

**Comment by bpmct** [comment]
Hi! Can you reach out on discord if you are still running into this? https://discord.gg/coder

**Comment by fferreira12** [comment]
> If you are running "Docker on Windows" this worked for me (Windows 10):
> 
> ...
> services:
>   coder:
>     image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
>     user: ${PUID}:${PGID} # <--- NEEDED
>     environment:
>       ...
>       PUID: ${PUID} # <--- NEEDED
>       PGID: ${PGID} # <--- NEEDED
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
> ...

This solution also worked on Ubuntu 24.04, if anyone else is having this issue. Thank you!

**Comment by seepine** [comment]
It cannot work for me on Ubuntu 24.01, create coder user and add to docker group
```
$ sudo id coder                  
uid=1003(coder) gid=1003(coder) groups=1003(coder),988(docker)
```
And create docker stack yml
```yml
version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-v2.17.3}
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "https://example.com"
      PUID: 1003
      PGID: 1003
    user: 1003:1003
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nas_disk/docker_volumes/code_server/coder:/home/coder

  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - /mnt/nas_disk/docker_volumes/code_server/pg:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
```
But create docker template go error
```
data.coder_provisioner.me: Refreshing...
data.coder_workspace_owner.me: Refreshing...
data.coder_workspace.me: Refreshing...
data.coder_provisioner.me: Refresh complete after 0s [id=5d20b246-9bf9-4330-82db-3327de0d19a2]
data.coder_workspace.me: Refresh complete after 0s [id=adf9c0d5-410a-43a2-ae64-9abda97407ee]
data.coder_workspace_owner.me: Refresh complete after 0s [id=55df557d-2004-478f-9922-2b2ca5dce02d]
coder_agent.main: Plan to create
coder_app.code-server: Plan to create
Plan: 2 to add, 0 to change, 0 to destroy.
Error: Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
on main.tf line 22, in provider "docker":
  22: provider "docker" {

```

**Comment by matifali** [comment]
Hi @seepine , You need to add `group-add: "998"` to `coder` service in your compose file

```yaml
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-v2.17.3}
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "https://example.com"
    group_add:
      - "998"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

...
```
