### DISCUSSION TITLE
Unhealthy of Access URL and Websocket

### DISCUSSION THREAD

**Discussion by seepine** [coder/coder#15967] [General]
I deploy with docker and proxy with traefik, the ssl with Let's Encrypt

```yml
version: "3"
services:
  coder_coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-v2.17.3}
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-coderusername}:${POSTGRES_PASSWORD:-password}@coderdatabase/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "https://code.traefik.example.com:1443"
    group_add:
      - "994"
    labels:
      - traefik.enable=true
      - traefik.http.routers.coder.rule=Host(`code.traefik.example.com`)
      - traefik.http.services.coder.loadbalancer.server.port=7080
      - traefik.http.routers.coder.tls.certresolver=myresolver        
      - traefik.http.routers.coder.tls.domains[0].main=*.traefik.example.com

# ...
```

### ACcessURL
EACS03: get healthz endpoint: Get "https://code.traefik.example.com:1443/healthz": context deadline exceeded
```
$ curl https://code.traefik.example.com:1443/healthz
[ok](curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to code.traefik.example.com:1443)
```
But Google chrome can got html text of `ok`

### WebSocket
EWS01: websocket dial: failed to WebSocket dial: failed to send handshake request: Get "https://code.traefik.example.com:1443/api/v2/debug/ws": context deadline exceeded

### Screen
<img width="250" alt="image" src="https://github.com/user-attachments/assets/65450b6e-d308-4dc1-b2ea-b19414ff0834" />
