### DISCUSSION TITLE
k3s load balancer issue

### DISCUSSION THREAD

**Discussion by guidogagl** [coder/coder#16024] [General]
Hi all !
I'm trying to build Coder on a k3s cluster of 4 nodes ( Ubuntu 20.04 ). I'm following the guide you updated on: 
https://coder.com/blog/running-coder-in-a-k3s-cluster-self-hosted
and
https://coder.com/docs/install/kubernetes

My main problem is when following the second guide is to assign an external IP address to the load balancer to update my DNS records with the coder domain, this is my values.yaml:

```yaml
coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url

    - name: CODER_ACCESS_URL
      # TODO
      value: "https://coder.mlpi.local"
    - name: CODER_WILDCARD_ACCESS_URL
      # TODO
      value: "*.coder.mlpi.local"
  
  service:
    enable: true
    type: LoadBalancer
    sessionAffinity: None
    externalTrafficPolicy: Cluster
    # coder.service.loadBalancerIP -- The IP address of the LoadBalancer. If not
    # specified, a new IP will be generated each time the load balancer is
    # recreated. It is recommended to manually create a static IP address in
    # your cloud and specify it here in production to avoid accidental IP
    # address changes.
    loadBalancerIP: ""
    loadBalancerClass: ""
    annotations: {}
    httpNodePort: ""
    httpsNodePort: ""
```

This way the load balancer got stuck in "pending" state while assigning the external IP address. I managed to solve this by installing metallb before installing coder ( this is my config file for metallb )

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.16.254.100-172.16.255.200
```
If I do this the load balancer assigns the external IP address, but this address is not reachable, am I missing something ?

Thank you a lot ! 
Guido
