### DISCUSSION TITLE
Error on first deployment: fails to create cache folder (error: create cache directory: mkdir /home/coder/.cache: permission denied)

### DISCUSSION THREAD

**Discussion by javierspn** [coder/coder#17782] [General]
Hi Team!

Before reporting an issue, I would like to know if someone has encountered this.

I follow the docker setup instructions and get the docker group to declare in group_add within the compose file, as the defaults gave me the error on the title:

`getent group docker | cut -d: -f3` (result is 994).

However whenever I start the stack I get this error multiple times:

`[getent group docker | cut -d: -f3](error: create cache directory: mkdir /home/coder/.cache: permission denied)`

This is my (partial) compose file:

```yaml
    group_add:
      - ${GROUP_ID}


    volumes:
      - ${CODER_SOCK_VOLUME}
      - ${CODER_HOME_VOLUME}
```
And the variables:

```shell
GROUP_ID=994
# CODER VOLUMES
CODER_SOCK_VOLUME=/var/run/docker.sock:/var/run/docker.sock
CODER_HOME_VOLUME=/docker/data/coder/home:/home/coder
```

Am I missing something?
