### ISSUE TITLE
Potential Memory Leak in 2.3

### ISSUE THREAD

**Issue by notwedtm** [coder/coder#10550]
After upgrading the coder helm chart from v2.2 to v2.3 on 10/20, we started seeing significant memory (tens of gigabytes), CPU (multiple cores), and constant container restarts.

CPU Usage:
![image](https://github.com/coder/coder/assets/52319902/f7d7d7ab-5174-4d3a-9f21-1d59f05facc3)

Memory Usage:
![image](https://github.com/coder/coder/assets/52319902/d3b3c145-6583-4050-8130-633ff92c4f7d)

Container Restarts: 
![image](https://github.com/coder/coder/assets/52319902/25d152b6-234d-480c-8167-b325a2eff012)

**Comment by ericpaulsen** [comment]
thank you for submitting this issue @notwedtm - can you confirm the version is `2.3.2`?

**Comment by notwedtm** [comment]
We have a fuzzy matcher in the Argo app:

```
repoURL: https://helm.coder.com/v2
chart: coder
targetRevision: ~> 2.3.2
```

This shows that we've been on `2.3.3` for about 7 days now.

**Comment by ammario** [comment]
cc @mafredri

**Comment by mafredri** [comment]
@notwedtm could you share what settings you are using for Coder? Of interest is especially whether or not you're using external/embedded DB, have enabled experimental coder settings, are using external provisioners, coder replicas, etc.

Would you also be able to share some pprof dumps from when you notice high memory usage? (This requires enabling pprof for `coder server` via `--pprof-enable` or `CODER_PPROF_ENABLE=true`.)

Essentially, we'd be interested in seeing the files produced by (see `/tmp/pprof` after running):

```
mkdir /tmp/pprof
for p in allocs heap goroutine; do wget -O /tmp/pprof/$p.gz http://localhost:6060/debug/pprof/$p; done
```

(The value of `http://localhost:6060` will depend on whether or not you've changed the pprof address and/or are running it on the same container as coder.)

**Comment by notwedtm** [comment]
We are running with an external DB (RDS Postgres). We are running with the kubernetes helm chart with the following config (sensitive values snipped):

```
coder:
  labels:
    tags.datadoghq.com/env: ops
    tags.datadoghq.com/service: coder
  podLabels:
    tags.datadoghq.com/env: ops
    tags.datadoghq.com/service: coder
    tags.datadoghq.com/version: 2.3.3
  podAnnotations:
    ad.datadoghq.com/coder.logs: '[{"source": "coder", "service": "coder"}]'
  tls:
    secretNames: 
      - coder-tls
  service:
    externalTrafficPolicy: Local
    sessionAffinity: None
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      external-dns.alpha.kubernetes.io/hostname: "<< SNIP >>"
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-credentials
          key: url
    - name: CODER_ACCESS_URL
      value: "<< SNIP >>"
    - name: CODER_REDIRECT_TO_ACCESS_URL
      value: "true"
    - name: CODER_WILDCARD_ACCESS_URL
      value: "<< SNIP >>"
    - name: CODER_OIDC_ISSUER_URL
      value: "<< SNIP >>"
    - name: CODER_OIDC_EMAIL_DOMAIN
      value: "<< SNIP >>"
    - name: CODER_OIDC_SIGN_IN_TEXT
      value: "<< SNIP >>"
    - name: CODER_DISABLE_PASSWORD_AUTH
      value: "true"
    - name: CODER_OIDC_GROUP_AUTO_CREATE
      value: "true"
    - name: CODER_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-auth
          key: CLIENT_ID
    - name: CODER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-auth
          key: CLIENT_SECRET
    - name: CODER_GITAUTH_0_ID
      value: "gitlab"
    - name: CODER_GITAUTH_0_TYPE
      value: "gitlab"
    - name: CODER_GITAUTH_0_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-gitlab-credentials
          key: GITLAB_CLIENT_ID
    - name: CODER_GITAUTH_0_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-gitlab-credentials
          key: GITLAB_CLIENT_SECRET
  ingress:
    host: "<<SNIP>>"
    tls:
      enable: true
      secretName: coder-tls
      wildcardSecretName: coder-tls
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: << IRSA ROLE >>
  volumes:
    - name: terraformrc
      secret:
        secretName: terraformrc
  volumeMounts:
    - name: terraformrc
      mountPath: /home/coder/.terraformrc
      subPath: .terraformrc
      readOnly: true
```

I'll work on getting a profiles running today and report back!
