### ISSUE TITLE
Coder version 2.5.0 coder ssh hanging

### ISSUE THREAD

**Issue by ygurin** [coder/coder#11217]
Since the upgrade from 2.4.0 -> 2.5.0, can't use the SSH feature.

```
╰─❯ ssh -vvvv coder.test123.main
OpenSSH_9.5p1, OpenSSL 3.2.0 23 Nov 2023
debug1: Reading configuration data /Users/yuri/.ssh/config
debug1: /Users/yuri/.ssh/config line 69: Applying options for coder.test123.main
debug1: Reading configuration data /opt/homebrew/etc/ssh/ssh_config
debug1: Executing proxy command: exec /opt/homebrew/bin/coder --global-config "/Users/yuri/Library/Application Support/coderv2" ssh --stdio test123.main
debug1: identity file /Users/yuri/.ssh/id_rsa type 0
debug1: identity file /Users/yuri/.ssh/id_rsa-cert type -1
debug1: identity file /Users/yuri/.ssh/id_ecdsa type -1
debug1: identity file /Users/yuri/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/yuri/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/yuri/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/yuri/.ssh/id_ed25519 type -1
debug1: identity file /Users/yuri/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/yuri/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/yuri/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/yuri/.ssh/id_xmss type -1
debug1: identity file /Users/yuri/.ssh/id_xmss-cert type -1
debug1: identity file /Users/yuri/.ssh/id_dsa type -1
debug1: identity file /Users/yuri/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.5
```

The web terminal works.

**Comment by matifali** [comment]
Hi @ygurin, are you able to reproduce this consistently? I am not able to reproduce.

**Comment by ygurin** [comment]
Ok, so when I was upgrading from `2.4.0` -> `2.5.0` I forgot to add `CODER_ACCESS_URL` as can be found in the [documentation](https://coder.com/docs/v2/latest/install/kubernetes). Now it works.

```
coder:
  # You can specify any environment variables you'd like to pass to Coder
  # here. Coder consumes environment variables listed in
  # `coder server --help`, and these environment variables are also passed
  # to the workspace provisioner (so you can consume them in your Terraform
  # templates for auth keys etc.).
  #
  # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
  # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
  # they are already set by the Helm chart and will cause conflicts.
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          # You'll need to create a secret called coder-db-url with your
          # Postgres connection URL like:
          # postgres://coder:password@postgres:5432/coder?sslmode=disable
          name: coder-db-url
          key: url

    # (Optional) For production deployments the access URL should be set.
    # If you're just trying Coder, access the dashboard via the service IP.
    - name: CODER_ACCESS_URL
      value: "https://coder.example.com"
```
