### ISSUE TITLE
`supportLinks` icons do not read `/icon/` directory or any icon URLs

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11611]
here's my `coder.yaml` file:

```yaml
supportLinks:
  - name: "Slack"
    target: "https://codercom.slack.com"
    icon: "/icon/slack.svg"
  - name: "GitHub"
    target: "https://github.com"
    icon: "/icon/github.svg"
```

the icons do not appear in the UI:

<img width="259" alt="Screenshot 2024-01-14 at 5 54 54 PM" src="https://github.com/coder/coder/assets/9683576/8f75ae2f-a189-4049-bf7a-9dbc334404a0">

**Comment by matifali** [comment]
Does not work with public URL links, either.
```yaml
supportLinks:
  - name: "GitHub"
    target: "https://github.com/coder/coder"
    icon: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg"
  - name: "Slack"
    target: "https://codercom.slack.com/archives/C014JH42DBJ"
    icon: "https://raw.githubusercontent.com/coder/coder/main/site/static/icon/slack.svg"
  - name: "Discord"
    target: "https://discord.gg/coder"
    icon: "https://raw.githubusercontent.com/coder/coder/main/site/static/icon/discord.svg"
````
![image](https://github.com/coder/coder/assets/10648092/9aca2deb-2bfa-4a48-a210-d2343145460c)
