### ISSUE TITLE
Documentation request: please add this solution for coder's embedded DERP server behind an istio ingress reverse proxy

### ISSUE THREAD

**Issue by valkenburg-prevue-ch** [coder/coder#11821]
I am very happy with the 'health' tab in the coder ui, which revealed to me that the embedded derp server was not accessible. The help documentation which I was then pointed to, was helpful as well. If you could add the following solution somehow somewhere, this will save all people with the same problem the two days it took me to find this solution.

When coder is installed inside an istio mesh, and your ingress is managed by istio, you have to apply the following manifest:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: headscale-behind-istio-ingress
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - upgrade_type: derp
```

which is directly derived from the solution found at https://github.com/juanfont/headscale/blob/main/docs/reverse-proxy.md#istio
