### ISSUE TITLE
Coder install error on bare metal Kubernetes

### ISSUE THREAD

**Issue by nikhilkamdar** [coder/coder#12709]
Hi,

I have a fully working K8 bare metal cluster and after following the instructions found here I fail at step 6 which is installing Coder after all the prerequisites have been configured: https://coder.com/docs/v2/latest/install/kubernetes

When the ghcr.io/coder/coder:v2.9.1 container tries to run it's outputting the following error message...

```
Started HTTP listener at http://0.0.0.0:8080
Using built-in PostgreSQL (/home/coder/.config/coderv2/postgres)
Encountered an error running "coder server"
Usage: coder server [flags]
Error: Failed to start built-in PostgreSQL. Optionally, specify an external deployment with `--postgres-url`: unable to connect to https://repo1.maven.org/maven2
Stream closed EOF for coder/coder-7bcf745478-c8gn4 (coder)
```

This assumes I have correctly configured everything as per the instructions for the postgres database which is up and running on its respective port and the 'coder-db-url' secret which is mapped into the values.yaml as per the installation instructions.

This is my secrets output:

```
NAME                             TYPE                 DATA   AGE
coder-db-url                     Opaque               1      12m
coder-tls-crt                    kubernetes.io/tls    2      17h
postgres-postgresql              Opaque               2      16m
sh.helm.release.v1.coder.v1      helm.sh/release.v1   1      10m
sh.helm.release.v1.postgres.v1   helm.sh/release.v1   1      16m
```

This is my services output:

```
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
coder                    LoadBalancer   10.111.88.69    192.168.3.51   80:31502/TCP   9m2s
postgres-postgresql      ClusterIP      10.105.20.163   <none>         5432/TCP       15m
postgres-postgresql-hl   ClusterIP      None            <none>         5432/TCP       15m
```

And for completeness my pods:

```
NAME                     READY   STATUS             RESTARTS        AGE
coder-7bcf745478-c8gn4   0/1     CrashLoopBackOff   7 (4m56s ago)   16m
postgres-postgresql-0    1/1     Running            0               22m
```

Has anybody encountered the same error or know if I completely missed something obvious to make the Coder container output that it cannot connect to the postgres container and trying to spin up its own internal one?

Many thanks

**Comment by kylecarbs** [comment]
You must not have the database URL set properly in the `values.yaml`.

The only way we start the embedded PostgreSQL is if the environment variable `CODER_PG_CONNECTION_URL` is missing.

**Comment by kylecarbs** [comment]
See step 5 in the docs. Maybe you have a typo!

**Comment by kylecarbs** [comment]
@nikhilkamdar lmk if that works!

**Comment by nikhilkamdar** [comment]
Thanks for the quick response, I am using this URL as this is how its shown on the YouTube install instructions but I think it was an error as it did not 100% match the container name: 
`postgres://coder:coder@postgres-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable`

So I tried changing the URL to match the container like in my original post:
`postgres://coder:coder@postgres-postgresql-0.coder.svc.cluster.local:5432/coder?sslmode=disable`

The DB was setup with the exact command from step 2 also, but I am still getting the same error output from the Coder container.

**Comment by kylecarbs** [comment]
Can you show me your `values.yaml` file?

**Comment by nikhilkamdar** [comment]
Of course...

```
coder:
  # You can specify any environment variables you'd like to pass to Coder
  # here. Coder consumes environment variables listed in
  # `coder server --help`, and these environment variables are also passed
  # to the workspace provisioner (so you can consume them in your Terraform
  # templates for auth keys etc.).
  #
  # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
  # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
  # they are already set by the Helm chart and will cause conflicts.
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          # You'll need to create a secret called coder-db-url with your
          # Postgres connection URL like:
          # postgres://coder:password@postgres:5432/coder?sslmode=disable
          name: coder-db-url
          key: url

    # (Optional) For production deployments the access URL should be set.
    # If you're just trying Coder, access the dashboard via the service IP.
    - name: CODER_ACCESS_URL
      value: "https://coder.example.com"
```

I can see in the docs this says that this is the bare minimum to get things running, but is there anything else that I should be adding to make this work?

Many thanks
