### ISSUE TITLE
Minikube: Creating Docker template fails

### ISSUE THREAD

**Issue by cschindlbeck** [coder/coder#12957]
I am following the [installation guide](https://coder.com/docs/v2/latest/install/kubernetes) on minikube and i have a minor issue that opening the LoadBalancer IP

```
> kubectl get svc -n coder
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
coder                    LoadBalancer   10.102.16.170   <pending>     80:31175/TCP   7s
coder-db-postgresql      ClusterIP      10.97.205.85    <none>        5432/TCP       71s
coder-db-postgresql-hl   ClusterIP      None            <none>        5432/TCP       71s
```

 does not work but with 

`kubectl port-forward service/coder 8080:80 -n coder`

i can access it on localhost, however i get the following error

```
Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
on main.tf line 19, in provider "docker":
  19: provider "docker" {
```

when creating the docker template. I made sure to install docker on minikube by logging in via `minikube ssh` and `docker ps -a` works inside, what am i missing here?

edit: `minikube tunnel` provides an ExternalIP but the other problem still persists

**Comment by matifali** [comment]
You need to mount the host docker socket to the coder pods as a volumemount.

**Comment by cschindlbeck** [comment]
This appears to be the problem, thanks, for everyone else wondering what to do:

> k edit deploy coder -n coder

```
        volumeMounts:
        - mountPath: /var/run/
          name: docker-socket
    [...]
      volumes:
      - hostPath:
          path: /var/run/
          type: ""
        name: docker-socket
```

However, docker.sock is not mounted with the correct permissions this way, so i changed the securityContext to privileged and than modified group of docker.sock to root, which might not be the cleanest way to do, but it works
