### ISSUE TITLE
ci: set up a github workflows linter

### ISSUE THREAD

**Issue by matifali** [coder/coder#13413]
As a follow-up, I think we should look into a github action linter to catch these problems pre-merge in the future.

Thanks for fixing @matifali 👍

_Originally posted by @dannykopping in https://github.com/coder/coder/pull/13412#pullrequestreview-2087660703_

**Comment by matifali** [comment]
We can borrow this snippet from https://github.com/coder/code-server

```yaml
lint-actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck= -ignore "set-output"
        shell: bash
```
