### ISSUE TITLE
Issues with OIDC causing control plane to crash

### ISSUE THREAD

**Issue by ccook-oteemo-com** [coder/coder#13987]
Self hosting Coder in a K8 cluster.   Setting the OIDC parameters via yaml (see below) to allow openid connect to function with keycloak. I try to hit local host and...  crash with no useful information in logs etc.
```
coder:
  # You can specify any environment variables you'd like to pass to Coder
  # here. Coder consumes environment variables listed in
  # `coder server --help`, and these environment variables are also passed
  # to the workspace provisioner (so you can consume them in your Terraform
  # templates for auth keys etc.).
  #
  # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
  # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
  # they are already set by the Helm chart and will cause conflicts.
  env:
  - name: CODER_PG_CONNECTION_URL
    valueFrom:
      secretKeyRef:
        # You'll need to create a secret called coder-db-url with your
        # Postgres connection URL like:
        # postgres://coder:password@postgres:5432/coder?sslmode=disable
        name: coder-db-url
        key: url
  - name: CODER_OIDC_ISSUER_URL
    value: "http://localhost:8080/realms/coder-realm"
  - name: CODER_OIDC_EMAIL_DOMAIN
    value: "oteemo.com"
  - name: CODER_OIDC_CLIENT_ID
    value: "coder-development-environment"
  - name: CODER_OIDC_CLIENT_SECRET
    value: "HduVU27PGYwykDRsR20KxjO6E2YZ6aeZ"
    # - name: CODER_VERBOSE
    #   value: 'true'
    # - name: CODER_OIDC_IGNORE_EMAIL_VERIFIED
    #   value: 'true'
    # - name: CODER_DISABLE_PASSWORD_AUTH
    #   value: true

# - name: CODER_OIDC_ISSUER_URL
#   value: "http://localhost:8080/realms/coder-realm/protocol/openid-connect/auth"
# - name: CODER_OIDC_EMAIL_DOMAIN
#   value: "localhost"
# - name: CODER_OIDC_CLIENT_ID
#   value: "coder-development-environment"
# - name: CODER_OIDC_CLIENT_SECRET
#   value: "HduVU27PGYwykDRsR20KxjO6E2YZ6aeZ"

#  env:
#     - name: CODER_OIDC_ISSUER_URL
#       value: "https://issuer.corp.com"
#     - name: CODER_OIDC_EMAIL_DOMAIN
#       value: "your-domain-1,your-domain-2"
#     - name: CODER_OIDC_CLIENT_ID
#       value: "533...des"
#     - name: CODER_OIDC_CLIENT_SECRET
#       value: "G0CSP...7qSM"


# (Optional) For production deployments the access URL should be set.
# If you're just trying Coder, access the dashboard via the service IP.
#- name: CODER_ACCESS_URL
#  value: "https://62.10.121.246"
#value: "https://coder.example.com"
# tls:
#   secretNames:
#   - tls-coder
#   port: 443
# tls:
#   enabled: "true"
#   secret: tls-secret
```
