### ISSUE TITLE
Coder Docker Container Stops Working / DB getting corrupted

### ISSUE THREAD

**Issue by MRLab12** [coder/coder#14092]
**Description**:

My Coder server, running in a Docker environment, is experiencing what looks to be intermittent database connection failures. These issues occur randomly, disrupting normal operations. I've tried to gather as much information I can for this issue, but haven't found many clues. 

I upgraded Coder around the same time I did a change to my `docker-compose.yaml` to fix a DB issue I was having. From what I have found, I believe the issue has to do with how my DB creds are set up. 

This is my current `docker-compose.yaml` file:

```
version: "3.9"
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: tailscale_coder
    ports: 
      - "TAILSCALE_IP:7080:7080"
      - "TAILSCALE_IP:13338:13338"
    environment:
     - TS_AUTHKEY=tskey-auth-kKs9hz5cGC11CNTRL-WsdMbXC22PB1a4BkRSc4PBqokq6DGM9Dj
     - TS_STATE_DIR=/var/lib/tailscale
     - TS_USERSPACE=false
    volumes:
     - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
     - /dev/net/tun:/dev/net/tun
    cap_add:
     - net_admin
     - sys_module
    restart: unless-stopped
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    #ports:
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      CODER_WILDCARD_ACCESS_URL: "*.coder.myserver.com:7080"
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
    group_add:
      - "999" # docker group on host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy
    network_mode: service:tailscale
  database:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} 
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  coder_data:

```
**Environment**:

- OS: Linux Sever Ubuntu 22.04.4 LTS

**Observed Behavior**:
1. Coder works fine most of the time.
2. Randomly, it loses the ability to connect to the database.
3. These connection issues sometimes resolve themselves without intervention. Most of the times, the DB is corrupted and I have to reset it.

**Logs**:

Database connection failures:
```
FATAL: password authentication failed for user "postgres"
DETAIL: Connection matched pg_hba.conf line 104: "host all all all scram-sha-256"
```

Frontend protocol error:
```
FATAL: unsupported frontend protocol 1234.5632: server supports 3.0 to 3.0
```

Other relevant log entries:
```
coder_1      | 2024-07-30 20:40:30.444 [info]  coderd.workspace_usage_tracker: updated workspaces last_used_at  count=1  now="2024-07-30T20:40:30.440513832Z"
tailscale_1  | 2024/07/30 20:40:33 Accept: TCP{100.96.27.25:64562 > 100.117.238.124:7080} 64 tcp ok
coder_1      | 2024/07/30 20:40:34 net/http: invalid Cookie.Domain ".coder.12thlab.com:7080"; dropping domain attribute
coder_1      | 2024-07-30 20:40:35.833 [warn]  coderd: GET  host=filebrowser--main--mariospace--feners.coder.12thlab.com:7080  path=/static/assets/medium-latin-qoGZqeje.woff2  proto=HTTP/1.1  remote_addr=100.96.27.25  start="2024-07-30T20:40:35.83239546Z"  took=1.399727ms  status_code=502  latency_ms=1  request_id=d4109b9b-4b52-4bd5-ad25-2160b86604d9 ...
```

**Additional Context**:

- The issue occurs without any apparent pattern or trigger.
- Database credentials have been verified and are correct.
- Network connectivity between containers appears stable based on Tailscale logs.
- The problem resolves itself without manual intervention.

**Steps to Reproduce**:

The issue occurs randomly and I haven't identified a reliable method to reproduce it on demand.

**Attempted Solutions**:

- Verified database credentials
- Checked network connectivity between containers
- Monitored resource usage (no apparent correlation found)

**Questions**:

1. Are there known issues with intermittent database connections in Docker deployments?
2. Could this be related to connection pooling or timeout settings?
3. Are there recommended logging or debugging techniques to better diagnose this issue?
<img width="1159" alt="Screenshot 2024-07-30 at 5 31 08 PM" src="https://github.com/user-attachments/assets/ec03dd5d-182c-48d4-9ef9-b7e3470643df">
<img width="1356" alt="Screenshot 2024-07-30 at 5 32 00 PM" src="https://github.com/user-attachments/assets/fd72e40f-4f3a-40f1-b5e1-f4ef52273d23">
