### ISSUE TITLE
Ensure all dependencies defined in `flake.nix` and our GitHub Actions are aligned

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#14343]
For example, I'm having a hell of a time trying to generate some protobuf definitions which pass CI because `protoc-gen-go` is not locked in our nix flake, while it's using a fixed version in `.github/workflows/ci.yaml`.

```yaml
      - name: go install tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30
```

```bash
[nix-shell:~/coder]$ protoc-gen-go --version
protoc-gen-go v1.34.2
```
