### ISSUE TITLE
Coder pods running out of memory

### ISSUE THREAD

**Issue by mambon2** [coder/coder#14881]
We've noticed over the past several months the coder pods gradually run out of memory over time.  Typically around 30 day mark but can't really say for sure.  Here is our memory allocation for a 5 replica set in k8s.

```
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 4000m
        memory: 8Gi
```

and here is a datadog screenshot of the memory usage around 30 day mark

![Screenshot 2024-09-23 at 7 15 33 PM](https://github.com/user-attachments/assets/b9428070-0487-4690-823a-200dfc9b5707)

Coder V2.13.4
We don't keep the k8s logs so not able to share those.

**Comment by dannykopping** [comment]
HI @mambon2,

Can you please clarify a few things for me?

1. What metric is being used here to calculate memory usage?
2. Do you have the `GOGC` or `GOMEMLIMIT` environment variables set?
3. There appear to be some marked jumps in memory usage in some of these processes; does this correlate to any events on your side?
4. Do your pods OOM once they reach 100%? If so, do you experience any downtime?

It would be helpful if you could share the Prometheus metrics of one of these processes with high memory usage as well as a pprof `heap` profile; that'll help us understand the problem more concretely.

**Comment by spikecurtis** [comment]
Also, can you look inside the pod and determine which processes are using memory? Coder server runs provisioners by default which start additional processes as part of provisioning.  It would be useful to understand whether it is the main server process that is using increasing memory.

**Comment by dannykopping** [comment]
Thanks for the detail @mambon2 

Regarding pprof, you'll need to enable `CODER_PPROF_ENABLE` and then you can navigate to the address specified in `CODER_PPROF_ADDRESS` (e.g. http://localhost:6060/debug/pprof/) to download the heap & goroutine profiles.

**Comment by mambon2** [comment]
As you can see from the above graph, the top 2 did not have any spikes but are trending upwards around 80% now.  The other 3 all have memory spikes exceeding 100%.

**Comment by mambon2** [comment]
> Thanks for the detail [@mambon2](https://github.com/mambon2)
> 
> Regarding pprof, you'll need to enable `CODER_PPROF_ENABLE` and then you can navigate to the address specified in `CODER_PPROF_ADDRESS` (e.g. http://localhost:6060/debug/pprof/) to download the heap & goroutine profiles.

@dannykopping do I use localhost or external DNS for this?

**Comment by mambon2** [comment]
I get an error as it looks like its trying to append a colon to the address string
```
parse "pprof Address": address http://localhost:6060/debug/pprof/: too many colons in address                                                                                                                           
```

**Comment by mambon2** [comment]
Unfortunately, we don't expose the individual pod IP addresses, so we can't navigate through the browser.  Can we download this using?
kubectl exec instead?

**Comment by spikecurtis** [comment]
If your pod has `curl` you should be able to `kubectl exec -n <namespace> <pod> -- curl http://localhost:6060/debug/pprof/heap > heap.out` and similarly for goroutine (`http://localhost:6060/debug/pprof/goroutine?debug=2`)

**Comment by mambon2** [comment]
I have enabled pprof now and pods have restarted and memory has gone back down.  When do you want to me to collect these? anytime?

**Comment by spikecurtis** [comment]
> I have enabled pprof now and pods have restarted and memory has gone back down. When do you want to me to collect these? anytime?

It would be most helpful to collect them once memory is anomalously high again.

**Comment by mambon2** [comment]
I'm attaching the 3 metrics in CVS format for Thursday Oct 31 - Friday Nov 1
[go_goroutines-data-2024-11-06 13_10_54.csv](https://github.com/user-attachments/files/17651309/go_goroutines-data-2024-11-06.13_10_54.csv)
[process_resident_memory_bytes-data-2024-11-06 13_11_16.csv](https://github.com/user-attachments/files/17651310/process_resident_memory_bytes-data-2024-11-06.13_11_16.csv)
[extract-2024-11-06T17_53_51.413Z-Memory Usage by Container.csv](https://github.com/user-attachments/files/17651311/extract-2024-11-06T17_53_51.413Z-Memory.Usage.by.Container.csv)

**Comment by mambon2** [comment]
@spikecurtis Yes the main concern is about the gradual memory increase.  However I asked Coder team if I should send these event as well and Nick Spangler suggested that I should.  Hence, yesterday's post.

To answer your question, no.  Have not noticed any correlated activity to any of these spikes.

**Comment by mambon2** [comment]
OK so this gave me an idea to check against the workspaces memory graph and it turns out they coincide.  here is the graph for Oct 31 - Nov 1 for memory usage of the workspaces.
![Image](https://github.com/user-attachments/assets/79fc9ca0-3195-45c9-9c14-0b144673d8cc)

If this is indeed the case, then you have something to start looking at.

**Comment by mambon2** [comment]
Next time this happens I can check if the workspace pod is running in the same node as the coderd pod.

**Comment by spikecurtis** [comment]
A gradual increase in memory over days is likely _not_ working as designed. That is to say, it sounds like a memory leak that we want to chase down, understand, and hopefully fix.

A short term spike in memory use might be working as designed, or it might not, depending on what caused the spike. If coderd is getting a huge increase in legitimate load (API requests, proxy traffic, etc.), then we reasonably expect its memory use to go up.  Have you checked API request rates, and network I/O during these spikes?

**Comment by mambon2** [comment]
Here is the memory graph for the past month and the pattern is alway trending upwards with intermittent spikes exceeding the 8G limit.
![Image](https://github.com/user-attachments/assets/bdb7cd18-61aa-43e5-b43c-a3d93de3a422)

**Comment by mambon2** [comment]
Here is where we stand for the past 12 hours.  2 pods are high at 88% memory used.  Let me know what if any other metrics you'd like to see for these 2 pods

![Image](https://github.com/user-attachments/assets/049b10b1-bd59-40d0-a3ed-c6c22340c18e)

**Comment by mambon2** [comment]
I'm attaching goroutine and heap pprof output for one of the 2 pods here.  I had to add txt extension to the files so I can attach them.  renamed them when you download.

[goroutine.out.txt](https://github.com/user-attachments/files/17780281/goroutine.out.txt)
[heap.out.txt](https://github.com/user-attachments/files/17780292/heap.out.txt)

**Comment by dannykopping** [comment]
Thanks for above, @mambon2.

These profiles don't seem to indicate any real problems to me, unfortunately.

Viewing the heap profile with `go tool pprof -http=: heap.out`:

![Image](https://github.com/user-attachments/assets/bf7ab45a-fadb-4da3-b684-228ca974a9c9)

This only shows 90MiB of data in-use (i.e. allocated and not released).

Similarly for the goroutines profiles:

![Image](https://github.com/user-attachments/assets/8001ad49-6d25-49b6-bbf7-361d0bd4d6cb)

I'm only seeing ~2K goroutines, much lower than what I would expect when it comes to the memory usage you're demonstrating here.

---

Even looking at your metrics shared in https://github.com/coder/coder/issues/14881#issuecomment-2460462211, the highest I can see the memory getting to is ~970MiB at 2024-11-01 13:48:00 which is around 25% of the requests based on what you mentioned in https://github.com/coder/coder/issues/14881#issue-2557169336.

---

Were these profiles/metrics collected during a peak? Based on the above data I'm not seeing much evidence of excessive memory.

Are you able to pull all the Prometheus metrics for these pods from their peak and send them to us? Since we cannot see the query for these datadog dashboards it's pretty difficult for us to understand what precisely we're looking at.

**Comment by dannykopping** [comment]
@mambon2 to clarify:

In [this message](https://github.com/coder/coder/issues/14881#issuecomment-2479683276) you said 2 pods were running high at 88% of their available memory. Are the profiles provided in [this message](https://github.com/coder/coder/issues/14881#issuecomment-2479755127) related to one of those pods in this high memory state?

**Comment by mambon2** [comment]
> [@mambon2](https://github.com/mambon2) to clarify:
> 
> In [this message](https://github.com/coder/coder/issues/14881#issuecomment-2479683276) you said 2 pods were running high at 88% of their available memory. Are the profiles provided in [this message](https://github.com/coder/coder/issues/14881#issuecomment-2479755127) related to one of those pods in this high memory state?

Yes

**Comment by dannykopping** [comment]
OK. Is it currently in a similar state? If you could send us a full set of metrics collected from that pod that'd be helpful.

**Comment by mambon2** [comment]
So the only metrics we're currently collecting are the ones Nick Spangle commented on earlier, except the 3rd one comes from datadog eks metrics, not prometheus.

go_goroutines - a drastic increase in goroutines can use up a lot of memory
process_resident_memory_bytes - the resident size of memory in the process
container_memory_usage_bytes - the total memory used per container

**Comment by dannykopping** [comment]
Let's start with those and see if we need additional context, thanks

**Comment by mambon2** [comment]
Here are the CSV files for one high memory pod for the last 24 hours
[go_goroutines-data-2024-11-19 09_53_29.csv](https://github.com/user-attachments/files/17816967/go_goroutines-data-2024-11-19.09_53_29.csv)
[process_resident_memory_bytes-data-2024-11-19 09_55_33.csv](https://github.com/user-attachments/files/17816984/process_resident_memory_bytes-data-2024-11-19.09_55_33.csv)

**Comment by mambon2** [comment]
We collect the container memory usage metric in datadog.  here is the CSV file for that
[extract-2024-11-19T15_22_57.299Z-Memory Usage by Container.csv](https://github.com/user-attachments/files/17817388/extract-2024-11-19T15_22_57.299Z-Memory.Usage.by.Container.csv)

**Comment by dannykopping** [comment]
The problem with datadog is that I don't know exactly what they're measuring, which is why we're requesting the `container_memory_usage_bytes` Prometheus metric. Memory usage is a very complicated & overloaded term, so if it's possible it'd be great to look at that metric which I've used before - unless we can find out precisely what datadog is measuring here.

The thing I'm really trying to understand here is the difference in heap and stack memory being used by the coder process. Goroutines have resizable stacks, but those won't show up in Go's heap profiles because the stack and the heap are two different memory regions. Maybe datadog has this level of introspection on the coder processes already? I know they do some very sophisticated introspection, but I think some of it is behind a paywall.

Knowing the total amount of memory the process is using combined with a heap profile should help us understand where the memory usage is coming from; if it's coming from the stack then it's a bunch of goroutines hanging around which shouldn't be.

**Comment by mambon2** [comment]
Datadog was quick to respond and it appears they are collecting the metric you are looking for

> kubernetes.memory.usage. Datadog Agent get this metric from [container_memory_usage_bytes](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) through cAdvisor API.

**Comment by dannykopping** [comment]
It seems like there's an order of magnitude difference in memory usage between `process_resident_memory_bytes` and `container_memory_usage_bytes`, which is weird. Do you have the `go_memstats_alloc_bytes` metric available? That'll specifically show us the heap size used by coderd.

**Comment by mambon2** [comment]
Good Morning, I'll include go_memstats_alloc_bytes in these CSV files from 1 of 2 pods which went above 92% memory this morning.  These are for the past 6 hours
[process_resident_memory_bytes-data-2024-11-21 08_57_10.csv](https://github.com/user-attachments/files/17846969/process_resident_memory_bytes-data-2024-11-21.08_57_10.csv)
[go_memstats_alloc_bytes-data-2024-11-21 08_56_37.csv](https://github.com/user-attachments/files/17846967/go_memstats_alloc_bytes-data-2024-11-21.08_56_37.csv)
[go_goroutines-data-2024-11-21 08_55_30.csv](https://github.com/user-attachments/files/17846968/go_goroutines-data-2024-11-21.08_55_30.csv)

**Comment by mambon2** [comment]
and here are the pprof output for that same pod before I restart it
[goroutine.out.txt](https://github.com/user-attachments/files/17847015/goroutine.out.txt)
[heap.out.txt](https://github.com/user-attachments/files/17847016/heap.out.txt)

**Comment by dannykopping** [comment]
Thanks very much for this, still not seeing any obvious culprits.

Could you please send through the k8s definition of your coder deployment?
We're thinking it could be something else in the container which is using the memory (such as using `emptyDir`).

**Comment by mambon2** [comment]
I'm sending you most of it here.  I left out the env: definitions.  This comes from helm values.yaml

```
  coder:
    replicaCount: 5
    podAnnotations:
      karpenter.sh/do-not-disrupt: "true"
      prometheus.io/scrape: "true"
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 4000m
        memory: 8Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                    - karpenter
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - coder
            topologyKey: kubernetes.io/hostname
    livenessProbe:
      initialDelaySeconds: 10
    service:
      enable: true
      type: ClusterIP
    ingress:
      enable: true
      className: alb
      host: coder.freewheel.tv
      annotations:
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:512783044785:certificate/972497ad-9b4b-4ab4-8ca5-2eb38f4ff113, arn:aws:acm:us-east-1:512783044785:certificate/321e9c85-24c2-4b94-9aa2-57d0dff28d3e
        ### Coder should only be accessible via FreeWheel VPN
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
        alb.ingress.kubernetes.io/healthcheck-path: /healthz
        ### refer to alb_ingress_group variable in terragrunt for the primary alb argocd uses
        alb.ingress.kubernetes.io/group.name: coder.primary-alb
        external-dns.alpha.kubernetes.io/hostname: prod.dev.coder.aws.fwmrm.net
        ### We use the public zone since private Beeswax zones cannot be resolved within FreeWheel VPN
        external-dns.alpha.kubernetes.io/zone-type: public
    env:
```
