### ISSUE TITLE
provisioner helm chart: stop requiring psk to be set

### ISSUE THREAD

**Issue by bpmct** [coder/coder#14985]
Now that we support `--key` auth and user auth, let's stop requiring a PSK secret in the provisionerd. As a workaround, the user can set the value to "" and use the key instead.

Secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: coder-org1-provisioner-key
type: Opaque
stringData:
  key: "the-key"
  psk: ""

```

Helm values:

```yaml
coder:
  env:
    - name: CODER_URL
      value: "https://dev.coder.com"
    - name: CODER_PROVISIONER_DAEMON_KEY
      valueFrom:
        secretKeyRef:
          name: coder-org1-provisioner-key
          key: key
  replicaCount: 1
provisionerDaemon:
  pskSecretName: coder-org1-provisioner-key
```

But we don't want to have users doing this long-term.

Let's also work with @EdwardAngert to update the provisioner docs to explain how to configure this in Helm
