### ISSUE TITLE
Workspace build failed terraform apply: exit status 1

### ISSUE THREAD

**Issue by KD-MM2** [coder/coder#14992]
```
Starting workspace
0 seconds
Terraform 1.9.2
docker_image.main: Plan to create
docker_container.workspace[0]: Plan to create
docker_image.main: Creating...
docker_image.main: Creation errored after 0s
Error: failed to read downloaded context: failed to load cache key: invalid response status 403

on main.tf line 167, in resource "docker_image" "main":
  167: resource "docker_image" "main" {
Cleaning Up
```

my compose file:
```
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    ports:
      - "3016:7080"
    env_file: .env
    restart: unless-stopped
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:16"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - /mnt/OTHER_DATAS/coder_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
```
![image](https://github.com/user-attachments/assets/3025ff87-d8ef-49da-9a3e-3d7a8915bca9)
