### ISSUE TITLE
Doc Issues Prometheus Integration

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#15385]
Hi Coders, found some doc issues on this page:

https://coder.com/docs/admin/integrations/prometheus

First error on the Service Monitor the port name is not matching based on the Service above.

Service Name: ` - name: prom-http`
Service Monitor Port Name: `- port: prometheus-http`

Second suggested changed. For some reason our target was not appearing on our prometheus targets, we had to add a namespaceSelector key on the Service Monitor to successfully appear

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations: []
  labels: {}
  name: coder-service-monitor
  namespace: coder
spec:
  endpoints:
  - interval: 10s
    port: prom-http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - coder
  selector:
    matchLabels:
      app.kubernetes.io/name: coder

```

Regards,
Mata
