### ISSUE TITLE
forks are unable to run ci because no access to secrets

### ISSUE THREAD

**Issue by matifali** [coder/coder#15557]
### Problem Description
Forked repositories cannot run CI workflows due to restrictions on accessing a sensitive license key required for E2E tests. This limitation blocks contributions from forks and prevents full validation of pull requests.  

### Desired Solution
Implement a secure mechanism to allow forks to pass CI workflows while protecting the license key.  

### Potential Approaches  
1. **Skip E2E tests for forks**: Run non-secret-dependent jobs for forks and reserve E2E tests for workflows triggered in the base repository.  
    ```yaml
    jobs:
      e2e-tests:
        if: github.repository == 'org/repo' # Run only in the base repository
    ```
2. **Ephemeral Licenses**: Generate short-lived license keys for PRs from forks, valid only for the duration of the CI workflow.
