### ISSUE TITLE
Allow standing up a Coder deployment without a built-in admin user and password

### ISSUE THREAD

**Issue by bpmct** [coder/coder#16640]
Some enterprises wish to manage Coder deployments entirely declaratively. Instead of setting up an admin user manually or via the CLI, [role sync](https://coder.com/docs/admin/users/idp-sync#role-sync) can be used to assign administrators.

Because of this, we should allow Coder to be deployed without the initial "set up" screen asking for an admin user account.

## Anticipated risks

As group/role sync is now configured at runtime via an admin, there is somewhat of a chicken/egg problem. Some vendors work around this with a Helm value for the initial username/password which can then be destroyed once Coder is stood up.

Alternatively, the perhaps initial group/role sync could be set as a helm value...

**Comment by bpmct** [comment]
Ah. I assumed we still had some concept of deployment role sync, like we did back when Coder was single-org. Yes. This has to tie to deployment roles

**Comment by mardonner** [comment]
Hey, in case this won't end up being implemented, is there another way to declaratively set up the initial owner user?

I'm deploying coder OSS via helm chart and would like to pass the initial admin user like the postgres connection URL:
```yaml
coder:
  env:
    - name: CODER_PG_CONNECTION_URL
       valueFrom:
         secretKeyRef:
         key: url
         name: coder-db-auth-url
```

Like this for example:
```yaml
coder:
  env:
    - name: CODER_INITIAL_OWNER_USER_EMAIL
       valueFrom:
         secretKeyRef:
         key: email
         name: coder-init-owner
    - name: CODER_INITIAL_OWNER_USER
       valueFrom:
         secretKeyRef:
         key: username
         name: coder-init-owner
    - name: CODER_INITIAL_OWNER_PASSWORD
       valueFrom:
         secretKeyRef:
         key: password
         name: coder-init-owner
```

I haven't tested it yet but maybe this could also work if the `coder server create-admin-user` command is idempotent. If that's the case, I can imagine passing this in the `lifecycle` block of the helm chart could also work:
```yaml
  lifecycle:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "coder server create-admin-user --username $CODER_INITIAL_OWNER_USER --password $CODER_INITIAL_OWNER_PASSWORD --email $CODER_INITIAL_OWNER_USER_EMAIL"]
```
The option to omit the password would also be nice to be able to have `CODER_DISABLE_PASSWORD_AUTH` set to false right from the start (so setting up this initial owner user with only OIDC auth. This would of course only work if OIDC properly set up. This is also not optimal because that would mean that the user cannot be deleted and will be recreated after a restart.

This would save me from headaches, if basic role sync (like described [here](https://github.com/coder/coder/issues/13110#issuecomment-2659206832)) remains a premium feature.

I'd really like to not have to reverse engineer the SQL that creates the owner user and build some custom construct that checks on startup if my owner user exists and fires an SQL Query on initial or every startup.

**Comment by gberche-orange** [comment]
thanks @mardonner for the hint, we successfully tested the following values.yaml with a slightly modified command to make it idempotent and succeed/fail based on the cli output. 

```yaml
  lifecycle:                                                                                                                                                                                                
    postStart:                                                                                                                                                                                              
      exec:                                                                                                                                                                                                 
        command:                                                                                                                                                                                            
          - /bin/sh                                                                                                                                                                                         
          - -c                                                                                                                                                                                              
          - coder server create-admin-user --username  username --email email --password 'password' 2>&1 | grep -E 'duplicate key value violates unique constraint|User created successfully'                                                                                                                                                                           
```

Seems that the post life cycle logs are unfortunately not streamed to pod logs, see https://stackoverflow.com/a/78229978/1484823
Adding a `tee /tmp/create-user.out` would enable troubleshooting and inspecting the coder command output.

Nb: as for the helm chart rendering, it would be preferable to not have the initial password in the deployment spec (as this may endup in kubemetrics), and rather generate a secret and mount this secret as a environment variable used in the postStart command

**Comment by mardonner** [comment]
@gberche-orange 
> Nb: as for the helm chart rendering, it would be preferable to not have the initial password in the deployment spec (as this may endup in kubemetrics), and rather generate a secret and mount this secret as a environment variable used in the postStart command

Could you elaborate on kubemetrics? Do you mean environment variables or the command? The deployment spec itself only references a secret, not contains it literally.

An option to let the helm chart generate a secret would be nice. If this is added, there should also be an option to let the user provide the secret themselves. Meaning that we should be able to reference an existing secret by its name and also be able to set which key in the secret maps to username, pw, mail etc.

In the end, the user creation should be part of some startup script. I imagine the only sensible way to pass the values from the secret to that is via environment variable. This would result in something like the example I gave above.

**Comment by gberche-orange** [comment]
@mardonner 
Thanks, +1 for keeping the deployment spec without credentials in inlined environment variable or command, just mounting external secret as env var using existing `coder.envFrom` property, and a referencing the variables in the command as your example showed.

I had missed this `coder.envFrom` property in quick my test and ended up hardcoding the secret in the command spec.

**Comment by mardonner** [comment]
We ended up using this, which seems to get the job done:

```yaml
coder:
# ...
  env:
    # ...
    - name: CODER_ADMIN_USERNAME
      value:  admin
    - name: CODER_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: coder-admin-credentials
          key: coder-admin-pw
    # ...
  lifecycle:                                                                                                                                                                                                
    postStart:                                                                                                                                                                                              
      exec:                                                                                                                                                                                                 
        command:                                                                                                                                                                                                                                                                                                                                                                                         
          - /bin/sh
          - -c
          - |
            {
              echo "--- Starting postStart hook at $(date) ---"
              # Wait for the server to be ready
              for i in $(seq 1 30); do
                if wget -qO- http://localhost:8080/healthz > /dev/null 2>&1; then
                  break
                fi
                sleep 2
              done

              # Attempt admin user creation
              coder server create-admin-user --username "$CODER_ADMIN_USERNAME" --email "coder-admin@admin.admin" --password "$CODER_ADMIN_PASSWORD" 2>&1 | grep -E 'duplicate key value violates unique constraint | User created successfully'
              echo "--- Hook finished with exit code $? at $(date) ---"
            } >> /tmp/post-start.log 2>&1
```

As stated before, this is certainly not the correct method to do this. A one off post install job or via a sidecar would probably be the correct method but I don't have the time to experiment with that right now.
