### ISSUE TITLE
coder-app cannot connect to coder server when coder is deployed offline with docker-compose and self-signed SSL cert

### ISSUE THREAD

**Issue by ParticleG** [coder/coder#16811]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

If we use CODER_ACCESS_URL to specify a direct HTTPS access, the coder-apps would always be spinning and never shows up, if we use NginX to reverse proxy HTTPS request to coder-server's HTTP port, and set CODER_ACCESS_URL to the *http* address, then access the *https* URL, then apps *can* be accessed, but health check icon remains a question mark. As long as CODER_ACCESS_URL is a HTTPS URL, we couldn't access coder-apps, no mater we use reverse proxy or not.

### Relevant Log Output

```shell

```

### Expected Behavior

CODER_ACCESS_URL can be set to a HTTPS URL and all app and management services are available

### Steps to Reproduce

Current partially working configs, with question mark on healthz-check
docker-compose.yaml:
```yaml
service:
  coder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7080"
      - “7443”
    environment:
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_TLS_ADDRESS: "0.0.0.0:7443"
      CODER_TLS_ENABLE: "true"
      CODER_TLS_CERT_FILE: "/etc/ssl/certs/cmwcoder.pem"
      CODER_TLS_KEY_FILE: "/etc/ssl/private/cmwcoder.key"
      CODER_TLS_CLIENT_AUTH: "none"
      CODER_TLS_ALLOW_INSECURE_CIPHERS: "true"

      CODER_ACCESS_URL: "http://cmwcoder.h3c.com"
      CODER_WILDCARD_ACCESS_URL: "*.cmwcoder.h3c.com"

      CODER_BLOCK_DIRECT: "true"
      CODER_DERP_SERVER_STUN_ADDRESSES: "disable"
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_DISABLE_NETWORK_TELEMETRY: "true"
      CODER_UPDATE_CHECK: "false"
    # ...
```
NginX config:
```properties
server {
  listen 80;
  server_name 10.113.36.121 cmwcoder.h3c.com;

  location / {
    proxy_pass http://127.0.0.1:7080/;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
  }

# ...
}

server {
  server_name 10.113.36.121 cmwcoder.h3c.com;
  listen 443 ssl;
  listen [::]:443 ssl ipv6only=on;

  ssl_certificate cmwcoder.pem;
  ssl_certificate_key cmwcoder.key;

  location / {
    proxy_pass https://127.0.0.1:7443/;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
  }

# ...
}
```

### Environment

- Host OS: Ubuntu 22.04
- Coder version: 2.19.0
