### ISSUE TITLE
Coder UI healthcheck yields EWS01: Failed to establish a WebSocket connection

### ISSUE THREAD

**Issue by santurini** [coder/coder#16892]
After installing Coder via Helm chart with a custom TLS ingress I was not able to connect to the created workspace, with the newly created pod logging:
```
2025-03-12 11:37:47.707 [info]  connecting to coderd

2025-03-12 11:37:47.795 [warn]  run exited with error ...

    error= GET https://coder.mydomain.com/api/v2/workspaceagents/me/rpc?version=2.3: unexpected status code 403: unexpected non-JSON response ""

               Error: no response body
```

While in the UI healthcheck tab I was getting `EWS01: Failed to establish a WebSocket connection`.

The error originates from the ingress configuration.
For anyone using Contour as ingress class, you have to enable websocket connection in the ingress annotation like this:
```YAML
ingress:
  enable: true
  className: contour
  host: coder.mydomain.com
  annotations:
    projectcontour.io/websocket-routes: "/"
  tls:
    enable: true
    secretName: mydomain.com
```

After updating the deployment, the healthcheck was succesfull as also the workspace creation and the connection via VSCode extension.
While for what concerns DERP upgrades, it seems there is still not an option to enable that in Contour
