### ISSUE TITLE
[BUG] Create workspace failed

### ISSUE THREAD

**Issue by mcdulltii** [coder/coder#3872]
## Coder with Docker

I'm using Coder through a docker-compose, with the compose file as below.

```
version: "3.5"

services:
  coder:
    image: docker.io/codercom/coder:1.34.0
    container_name: coderd
    restart: unless-stopped
    networks:
      - coder
    ports:
      - 7080:7080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/var/run/coder
    environment:
      DB_EMBEDDED: ""
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: redacted
      DB_NAME: postgres
      DB_SSL_MODE: disable
    depends_on:
      - db

  db:
    container_name: coderd_db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    networks:
      - coder
    environment:
      POSTGRES_PASSWORD: redacted
    volumes: 
      - db-data:/var/lib/postgresql/data

networks:
  coder:
    external: false

volumes:
  config:
  db-data:
```

I'm using the `codercom/enterprise-base:ubuntu` image within Coder.

![image](https://user-images.githubusercontent.com/30497633/188446271-9175a766-8f06-4750-b467-0a1cb065675a.png)

I have tried creating a new workspace, with the container-based option checked on and off. However, in both workspaces, the workspace creation fails with the error message below.

![image](https://user-images.githubusercontent.com/30497633/188446616-e9f43185-2886-4328-bf43-95b9e474c088.png)

I'm currently running Coder on my domain, and have changed my access URL on the admin config accordingly.

The error log message is as shown below.

![image](https://user-images.githubusercontent.com/30497633/188447086-ad611f2c-0a2f-452a-8f7e-28b437aa7950.png)

According to the error message, `/var/run/docker.sock` is POST-ed and prepended with a `http://`. May I get some help on resolving this issue?
