### ISSUE TITLE
Helm: support ingress configuration

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#3959]
a prospective customer attempted to deploy Coder on k8s in Azure, with an Application Gateway (ingress) handling end to end TLS. currently this is not supported, because we do not provision an ingress resource that integrates with a separately managed controller.

**Comment by ericpaulsen** [comment]
here's a sample ingress YAML i sent to the prospect:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder-ingress
spec:
  tls:
    - hosts:
        - "<your-host>"
      secretName: "codeross-tls-secret"
  ingressClassName: ""
  rules:
  - host: "<your-host"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coder
            port:
              name: http
```
