### ISSUE TITLE
helm: upgrading with latest coder image returns db migration error

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#4606]
attempted to upgrade my helm deploy of Coder, 0.9.1, to latest. my `values.yaml` file referenced the following for the coder image:

```
coder:
  replicaCount: 3
  image:
    pullPolicy: IfNotPresent
    repo: ghcr.io/coder/coder
    tag: latest
```

out of the 3 coder replicas, one went into a `CrashLoopBackOff` state, with this error in the logs:

```
migrate up: up: no migration found for version 61: read down for version 61 .: file does not exist
```

the other 2 replicas were in a `Running` state, but the logs returned this error:

```
"error": acquire job: pq: column "storage_source" does not exist
```

i fixed this by setting `coder.image.tag=v0.10.0` in my values file. my hunch is that the `IfNotPresent` pull policy is preventing K8s from pulling the newest digest of `latest`, because `ghcr.io/coder/coder:latest` is technically present on the host. meanwhile the migrations container is running with nothing to migrate. thoughts, suggestions?
