### ISSUE TITLE
`docker-compose` installation fails on startup

### ISSUE THREAD

**Issue by peterchappy** [coder/coder#4963]
For the life of me I cannot seem to get the `docker-compose` installation up and running. I'm running it behind a reverse proxy `nginx` server in the same `docker-compose.yaml` On boot, I get 

```
nginx-coder-1     | ==> Logs will stream in below (press ctrl+c to gracefully exit):
nginx-coder-1     | Unexpected error, shutting down server: install terraform: install: Get "https://releases.hashicorp.com/terraform/1.3.0/index.json": dial tcp: lookup releases.hashicorp.com on 127.0.0.11:53: read udp 127.0.0.1:34838->127.0.0.11:53: i/o timeout
nginx-coder-1     | Shutting down API server...
nginx-coder-1     | Gracefully shut down API server
nginx-coder-1     | Waiting for WebSocket connections to close...
nginx-coder-1     | Done waiting for WebSocket connections
```

I'm hoping there is an obvious answer I'm missing something. Here is my `docker-compose.yml`

```
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./error_log.log:/etc/nginx/error_log.log
      - ./cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./html:/app/static
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  coder:
    # This MUST be stable for our documentation and
    # other automations.
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    ports:
      - 7080:7080
    user: "1000:999"
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_ADDRESS: "0.0.0.0:7080"
      # You'll need to set CODER_ACCESS_URL to an IP or domain
      # that workspaces can reach. This cannot be localhost
      # or 127.0.0.1 for non-Docker templates!
      CODER_ACCESS_URL: "${MY_IP}"
#      CODER_ACCESS_URL:"${MY_URL}"
    # If the coder user does not have write permissions on
    # the docker socket, you can uncomment the following
    # lines and set the group ID to one that has write
    # permissions on the docker socket.
#    group_add:
#      - "999" # docker group on host
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
  database:
    image: "postgres:14.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username} # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ${POSTGRES_DB:-coder} # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - coder_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  coder_data:
networks:
  host:
    name: host
    external: true
```
