### ISSUE TITLE
packages.yaml workflow does not run on a new release.

### ISSUE THREAD

**Issue by matifali** [coder/coder#5137]
[`packages.yaml`](https://github.com/coder/coder/blob/main/.github/workflows/packages.yaml) was merged in `main` before `0.12.7` and `0.12.8` releases but it did not run both of the times.

It seems like the trigger,
```yaml
on:
  release:
    types: [published]
```
is not working.

There is some context and a similar issue.  https://github.com/googleapis/release-please/issues/766

A workaround can be to change the trigger to,
```yaml
on:
  workflow_run:
    workflows: [release]
    types:
      - completed
```
This will run the workflow after the release workflow.

Another approach is to create a separate token, as discussed here, https://github.com/orgs/community/discussions/26875

cc @deansheather
