### ISSUE TITLE
No token via coder login ...

### ISSUE THREAD

**Issue by 1Turtle** [coder/coder#5847]
### Description
Hey!
So I setup coder via the docker-compose file. It all runs healthy and the Web UI is reachable too as intended.

I dont have any user setup. Because:
**To create one, I have to first login via `coder login <my_domain>`.**
It then tells me that my browser has been opened to visit the corresponding website and that I should paste my token now.
*(The website it returned is something like `<my_domain>/cli-auth` btw.)*

### Problem
My Problem now is that it did not opened a browser. And when I follow the domain I get the following message:

![grafik](https://user-images.githubusercontent.com/53350357/214426278-20a46fc8-a5d0-4357-b2bd-0a12989f7c88.png)

### Details
I dont know how to continue the setup. With the tunnel for test purposes I dont have such problems. Its only if I try this with my domain.

The following fields from the docker compose file might be good to know:
```yml
version: "3.9"
services:
  coder:
    image: ghcr.io/coder/coder:latest
    ports:
      - "7080:7080"
    environment:
      CODER_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: https://example.org # I DONT USE THIS DOMAIN, THIS IS JUST A EXAMPLE

# ...
```
