### ISSUE TITLE
Add `podAnnotations` to the Helm chart

### ISSUE THREAD

**Issue by FaresHerhar** [coder/coder#6695]
### Description
For some reason I'm not able to make pull requests, so I am suggesting to add this small feature to the Helm Chart.

I needed to add annotations to the the coder pod, but it is not possible with the current Helm Chart. So the idea is to add `podAnnotations: {}` into the [`helm/values.yaml`](https://github.com/coder/coder/blob/main/helm/values.yaml)  file, and add the pod annotations to the coder pod, into the [`helm/templates/coder.yaml`](https://github.com/coder/coder/blob/main/helm/values.yaml) file, as the following:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder
  labels:
    {{- include "coder.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.coder.annotations | nindent 4}}
spec:
  replicas: {{ .Values.coder.replicaCount }}
  selector:
    matchLabels:
      {{- include "coder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coder.labels" . | nindent 8 }}
      ######################################################
      annotations:
        {{- with .Values.coder.podAnnotations}}
        {{- toYaml . | nindent 8  }}
        {{- end}}
      ######################################################
    spec:
      serviceAccountName: {{ .Values.coder.serviceAccount.name | quote }}
      restartPolicy: Always
```
