### ISSUE TITLE
Add way to mount additional secrets via Coder helm chart

### ISSUE THREAD

**Issue by alexander-dammeier** [coder/coder#6794]
Hello,

to provision VMs in the Google Cloud we always need to copy a service account json file to the coder pod, so that terraform can use it as described [here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#adding-credentials). We add the `GOOGLE_APPLICATION_CREDENTIALS` env var which points to the location of the credentials.json file. As the helm template does not provide a way to copy the file while updating our pod with it, we manually copy the file every time.

A generic solution for that problem would be to let users mount preexisting secrets to the coder pod.

**Comment by ericpaulsen** [comment]
hi @alexander-dammeier - thank you for submitting this issue. our Helm chart supports your use-case. here are the steps:

1. create the `credentials.json` file as a secret in the same namespace where you're installing/upgrading Coder

```
kubectl create secret generic google-creds-secret -n coder --from-file=credentials.json
```

2. create a volume & volumeMount to mount the existing secret into the Coder pod. here's an example `values.yaml` that does so:

```
coder:
  volumes:
  - name: "secrets-mount"
    secret:
      secretName: "google-creds-secret"
  volumeMounts:
  - name: "secrets-mount"
    mountPath: "/mnt/secrets"
    readOnly: true
```

3. once deployed, you should be able to view the file contents by running the following command:

```
kubectl exec <coder-pod> -n coder cat /mnt/secrets/credentials.json
```
