### ISSUE TITLE
Use ssh key inside a devcontainer

### ISSUE THREAD

**Issue by bilby91** [coder/coder#7508]
Hello,

I would like to start by just saying that coder is awesome ❤️!

I'm currently implementing Coder for our internal projects at Crunchloop. We are starting to use Coder to deploy VMs using fly.io. The coder workspaces are really simple for us in terms of provisioning since we literally create them so that we can spin up devcontainers.

At the moment we have a configuration that is working but there are some details that we want to improve. One of those things that is bugging us is the ability to reuse the ssh key that Coder "injects" for us in the workspace. Since we work at the devcontainer layer, we can't use the `GIT_SSH_COMMAND` that is configured in fly.io VM (or at least that is my understanding). Coder doesn't seem to deploy a standard SSH Agent where we can do Agent Forwarding. If we would be able to have a standard SSH Agent running, we would be able to connect to the Dev Containers using ssh and enable forwarding. I've been doing this in the past in different linux hosts when running devcontainers.

So, I'm wondering if there is any workaround that we can do in order to inject/proxy the private key to the devcontainers or expose them in some kind of fashion.

Looking forward for any feedback!

**Comment by bilby91** [comment]
I was able to get this working in a hacky way.

Snippet of the relevant pieces of my docker-compose file used by the devcontainer in case someone finds it useful.

```yaml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # `GIT_ASKPASS` holds a pointer to the coder binary that is used
      # by `GIT_SSH_COMMAND` to interact with coder's private ssh key.
      - $GIT_ASKPASS:$GIT_ASKPASS

    environment:
      # Replace `ssh` with coder's implementation
      #
      - GIT_SSH_COMMAND=$GIT_SSH_COMMAND

      # We need the following varibales to be able to invoke `GIT_SSH_COMMAND`
      # successfully
      #
      - CODER_AGENT_AUTH=$CODER_AGENT_AUTH
      - CODER_AGENT_TOKEN=$CODER_AGENT_TOKEN
      - CODER_AGENT_URL=$CODER_AGENT_URL
```
