### ISSUE TITLE
awscli in Coder server container

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#8263]
Hi! We're looking to connect Coder to an AWS EKS cluster. We'd like to use the `aws eks get-token` authentication method, which looks like this in the Kubeconfig:

```yaml
users:
- name: arn:aws:eks:eu-west-1:XUZ:cluster/main
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - main
      - --role
      - arn:aws:iam::XUZ:role/AmazonEKSAdmin
      command: aws
      env:
      - name: AWS_ACCESS_KEY_ID
        value: ...
      - name: AWS_SECRET_ACCESS_KEY
        value: ...
```

Unfortunately this doesn't work right now because the AWS CLI is not available on Coder. Is there any chance it can be included in the Coder server image, or do you have a recommendation on how to proceed here?

Thank you
