### ISSUE TITLE
Environment variable value in GitHub authentication documentation should be quoted

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9033]
The [Authentication documentation](https://coder.com/docs/v2/latest/admin/auth) has the following configuration block for Kubernetes:

```
coder:
  env:
    - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
      value: true
    - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
      value: "your-org"
    - name: CODER_OAUTH2_GITHUB_CLIENT_ID
      value: "533...des"
    - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
      value: "G0CSP...7qSM"
    - name: CODER_OAUTH2_GITHUB_ALLOW_EVERYONE
      value: true
```

The values `true` need to be quoted (`"true"`) or else they will not be interpreted as strings and the deployment will fail.

**Comment by kylecarbs** [comment]
Thanks for reporting. Will fix!

**Comment by ryansburgoyne** [comment]
You may also want to suggest using a secret for the GitHub secret and

```yaml
valueFrom:
  secretKeyRef:
    name: coder-oauth2-github-client
    key: secret
```
