### ISSUE TITLE
Enabling Traefik HTTPS redirect middleware breaks websockets

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9035]
Yesterday, I installed Coder OSS on my Kubernetes cluster. It installed fine, but the CLI commands all failed and I couldn't connect to any workspaces.

I finally figured out the problem. I had configured the ingress for accessing Coder with a Traefik middleware to redirect to HTTPS:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-secure
  namespace: tenant-test-default
spec:
  redirectScheme:
    permanent: true
    scheme: https
```

This resulted in a bunch of attempts to reach URLs starting with `https://wss://`.

I removed the middleware, but this meant that users wouldn't be automatically redirected to HTTPS. So I worked around that by proxying through Cloudflare and enabling "Always Use HTTPS" there.

I don't know if this is a Traefik problem (I couldn't find any way to fix it on that end) or something that can be handled in Coder, but I thought I'd share my experience in case it's something that can be fixed.

_Originally posted by @ryansburgoyne in https://github.com/coder/coder/discussions/9032_
