### ISSUE TITLE
Self Signed Certificate in Kubernetes Secret not accepted

### ISSUE THREAD

**Issue by simonjcarr** [coder/coder#9403]
I am installing Coder in an Air Gapped Environment. Code Server is up and running and I can connect to it and log in.

The problem is I am getting errors in the workspace pod relating to the certificate. 

```
command -v curl
curl -fsSL --compressed https://coder.my-domain.lan/bin/coder-linux-amd64 -o coder
curl: (60) SSL certificate problem: unable to get local issuer certificate
```
This leads to the next error
```
status=60
echo error: failed to download coder agent
echo        command returned: 60
echo Trying again in 30 seconds...
```

I can confirm the SSL error by doing a manual curl to the LoadBalancer IP Address of coder, I have to use the -k option to ignore TLS in order to get a response from the coder server. 

My values.yaml looks like this

```
coder:
  # You can specify any environment variables you'd like to pass to Coder
  # here. Coder consumes environment variables listed in
  # `coder server --help`, and these environment variables are also passed
  # to the workspace provisioner (so you can consume them in your Terraform
  # templates for auth keys etc.).
  #
  # Please keep in mind that you should not set `CODER_ADDRESS`,
  # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
  # they are already set by the Helm chart and will cause conflicts.
  image:
    repo: "x.x.x.x:8191/coder/coder"
    pullPolicy: Always
    tag: "v2.1.0-1"

    
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          # You'll need to create a secret called coder-db-url with your
          # Postgres connection URL like:
          # postgres://coder:password@postgres:5432/coder?sslmode=disable
          name: coder-db-url
          key: url
    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.my-domain.lan"

    # (Optional) For production deployments the access URL should be set.
    # If you're just trying Coder, access the dashboard via the service IP.
    - name: CODER_ACCESS_URL
      value: "https://coder.my-domain.lan"

  tls:
    secretNames:
      - coder-tls
```

I have created a `kubernets.io/tls` certificate which amongst other domains includes `*.my-domain.lan`.
```
kubectl get secret -n coder
NAME                             TYPE                 DATA   AGE
coder-db-postgresql              Opaque               2      5d3h
coder-db-url                     Opaque               1      7d19h
coder-tls                        kubernetes.io/tls    2      114m
sh.helm.release.v1.coder-db.v1   helm.sh/release.v1   1      5d3h
sh.helm.release.v1.coder.v1      helm.sh/release.v1   1      4d21h
sh.helm.release.v1.coder.v2      helm.sh/release.v1   1      165m
sh.helm.release.v1.coder.v3      helm.sh/release.v1   1      113m
sh.helm.release.v1.coder.v4      helm.sh/release.v1   1      35m
sh.helm.release.v1.coder.v5      helm.sh/release.v1   1      32m
sh.helm.release.v1.coder.v6      helm.sh/release.v1   1      19m
```
